"""
Agent State — defines the shared state that flows through the LangGraph workflow.
"""

from typing import Annotated, Any, Optional, Sequence
from typing_extensions import TypedDict

from langchain_core.messages import BaseMessage
from langgraph.graph.message import add_messages


class AgentState(TypedDict):
    """
    Shared state for the multi-agent LangGraph workflow.

    Fields:
        messages:           Accumulated LLM message history (auto-appended via add_messages).
        user_query:         The original user question or task.
        repo_id:            ID of the target repository.
        repo_path:          Local filesystem path of the cloned repo.
        plan:               Step-by-step plan generated by the Planner agent.
        retrieved_context:  Code chunks retrieved by the Retrieval agent.
        tool_results:       Outputs from tool invocations by the Tool agent.
        final_answer:       The synthesized final response from the Execution agent.
        current_step:       Index of the current plan step being executed.
        needs_tools:        Whether the Planner decided tools are needed.
        error:              Error message if any step fails.
        steps_log:          Log of each agent step for observability.
    """

    messages: Annotated[Sequence[BaseMessage], add_messages]
    user_query: str
    repo_id: str
    repo_path: str
    plan: list[str]
    retrieved_context: list[dict]
    tool_results: list[dict]
    final_answer: str
    current_step: int
    needs_tools: bool
    error: Optional[str]
    steps_log: list[dict]
